### ISSUE TITLE
建议统一下条件变量名呢

### ISSUE THREAD

**Issue by young40** [yomunsam/TinaX.VFS#1]
```
#if TINAX_DEV
    [CreateAssetMenu(fileName =XILConst.ConfigFileName)]
#endif
```

```
#if TINAX_DEBUG_DEV
    [CreateAssetMenu(fileName = "vfsConfig",menuName = "TinaX/Development/VFS/创建Config文件")]
#endif
```

**Comment by yomunsam** [comment]
emm，其实它两意思还不完全一致，

以及这个宏设计时候没打算对外开放，

嘛，啥时候抽个时间给整理整理吧

**Comment by young40** [comment]
大佬回复好神速!

我给Unity加了这俩定义, ILRuntime的菜单出来了一次, 我加好之后, 再也看不到了.
VFS这个菜单倒腾俩小时了, 还没出来呢.
是不是要从Demo里面复制一个配置文件出来呢.

Setting里面这么配置的.
![WX20210120-164249](https://user-images.githubusercontent.com/1680953/105149557-a0466500-5b3e-11eb-96a8-0629ee50df7f.png)

**Comment by yomunsam** [comment]
> 大佬回复好神速!
> 
> 我给Unity加了这俩定义, ILRuntime的菜单出来了一次, 我加好之后, 再也看不到了.
> VFS这个菜单倒腾俩小时了, 还没出来呢.
> 是不是要从Demo里面复制一个配置文件出来呢.
> 
> Setting里面这么配置的.
> ![WX20210120-164249](https://user-images.githubusercontent.com/1680953/105149557-a0466500-5b3e-11eb-96a8-0629ee50df7f.png)

不需要这些操作的啊，如果正常使用的话，包装好了直接就用了。如果用ILRuntime的话，ILRuntime自己是独立的包，

没必要折腾这些啊，这几个宏定义是框架开发者内部调试用的

**Comment by young40** [comment]
主要不是这俩宏, 是创建vfs, ilruntime对应的配置文件.

我是从零开始配置的项目, 包安装也是用的OpenUPM的命令装的.

装好之后, 还是需要创建vfsConfig, 以及XILRTConfig的config.

没有这俩菜单, 好像没有别的方式创建这里配置文件.(我Unity新手哈)

缺了vfs的配置, 启动TinaX时会报错OnServicesStartException.
`
TinaX.VFSKit.Exceptions.VFSException: [TinaX.VFS]Load VFS config failed
`

PS: 我暴力修改了项目Library下面对应包的cs文件, 打开了菜单, 创建好了.

**Comment by yomunsam** [comment]
> 主要不是这俩宏, 是创建vfs, ilruntime对应的配置文件.
> 
> 我是从零开始配置的项目, 包安装也是用的OpenUPM的命令装的.
> 
> 装好之后, 还是需要创建vfsConfig, 以及XILRTConfig的config.
> 
> 没有这俩菜单, 好像没有别的方式创建这里配置文件.(我Unity新手哈)
> 
> 缺了vfs的配置, 启动TinaX时会报错OnServicesStartException.
> `TinaX.VFSKit.Exceptions.VFSException: [TinaX.VFS]Load VFS config failed`
> 
> PS: 我暴力修改了项目Library下面对应包的cs文件, 打开了菜单, 创建好了.

情况是这样的，框架给业务开发者暴露的所有功能的设置菜单，都统一在编辑器的`ProjectSettings`窗口里，基本上不会有菜单的

**Comment by young40** [comment]
> > 主要不是这俩宏, 是创建vfs, ilruntime对应的配置文件.
> > 我是从零开始配置的项目, 包安装也是用的OpenUPM的命令装的.
> > 装好之后, 还是需要创建vfsConfig, 以及XILRTConfig的config.
> > 没有这俩菜单, 好像没有别的方式创建这里配置文件.(我Unity新手哈)
> > 缺了vfs的配置, 启动TinaX时会报错OnServicesStartException.
> > `TinaX.VFSKit.Exceptions.VFSException: [TinaX.VFS]Load VFS config failed`
> > PS: 我暴力修改了项目Library下面对应包的cs文件, 打开了菜单, 创建好了.
> 
> 情况是这样的，框架给业务开发者暴露的所有功能的设置菜单，都统一在编辑器的`ProjectSettings`窗口里，基本上不会有菜单的

感谢大佬, ProjectSettings确实可以创建这俩文件. 
是我对这个框架还不太熟悉
