### ISSUE TITLE
关于GroupHandleMode.LocalOrRemote处理的疑问

### ISSUE THREAD

**Issue by young40** [yomunsam/TinaX.VFS#3]
大佬, 您好.

我看了下当group设置为LocalOrRemote后, 打包时, 并不会把该group放置一份到vfs_remote, 导致需要更新时, 下载新资源失败

看了下相关代码, 似乎是LocalOrRemote被Profile(Profile中设置为默认设置local)影响, 导致只会在local中生成相关资源.
https://github.com/yomunsam/TinaX.VFS/blob/562d1f95a92eea79d9a584a36900976706638ff5/Editor/Builder/VFSBuilder.cs#L465-L476

我不太明白, 为什么group放在本地还是在远程, 同时会被group本身设置和Profile影响, 并且Profile对group的设置没有LocalOrRemote选项呢?

**Comment by yomunsam** [comment]
group的LocalOrRemote指的是runtime的加载逻辑：这个group的资源会尝试去remote加载，也可以从本地加载。
group不会去管编辑器下的打包逻辑。

而profile则是告诉编辑器怎么来打包的，怎么加载它不管。

这是两套相对独立的东西

**Comment by young40** [comment]
我打算实现一个所有(尽可能)内容都能被热更新的游戏, 也希望热更新界面也可以被热更新(可能需要下次启动游戏才生效).

因为有热更新界面, 所以需要把热更新界面打到包里面去, 否则玩家第一次启动时, 如果网络慢, 会有较长时间没有界面(游戏启动后可能会先下载热更新界面本身)

因为计划是所有界面都可以更新, 所以就不打算分很多group, 用了默认的common这个group.

只有一个group, 所以要求该group是LocalOrRemote. 即可以被打进包里面, 也可以作为可以热更的资源.

我的操作是这样的:
配置是: common group设置为LocalOrRemote, Profile该group设置为Local
1. 通过VFS Builder, 先Build一下, 并且选中复制到StreamingAssets
2. 创建一个版本v0, 启动Web服务器
3. 打包一个app. 
4. 对UI进行修改后, 通过VFS Builder, Build后创建版本v1, 
5. 打开第三步中创建的app
这时会看到启动报错.
报找不到 http://127.0.0.1:8080/files/osx/vfs_remote/assets/ui/superpowerentry/superpowerentry.prefab.xab

**Comment by young40** [comment]
UnityEditor里面能不能完全模拟App启动, 访问更新, 下载更新这些行为?

用App不太好用C#调试.

**Comment by yomunsam** [comment]
emm，这样的，vfs里有补丁包和webvfs两套机制，你好像把它们混在一起理解了。
这儿有一些介绍：https://zhuanlan.zhihu.com/p/113443082

目前市面上游戏常用的更新方式，也就是tinax中的补丁包机制（https://zhuanlan.zhihu.com/p/76824769）：
1. 通过打包和版本差异得到补丁
2. 由于不同业务需求，对下载补丁、更新补丁的规则和时机并不统一，所以目前框架并不提供补丁的完全不用操心的通用银弹。开发者应该根据自己的逻辑来处理补丁
3. 框架默认提供了根据版本打包的编辑器工具和安装补丁的简单API，对于没有特殊需求的业务可以直接用。
4. 补丁包本身就是个zip包，有特殊业务需求的开发者也可以自己实现一套打补丁、安装补丁的流程


## WebVFS
WebVFS是另一套机制，同一个项目可以同时存在补丁机制和WebVFS机制，但单个Group只能适用其中一种机制。
WebVFS的思路如下：
1. 把资产全部打包成尽可能细粒度的assetbundle
2. 把打包后的ab包全传到服务器
3. webvfs没有版本号概念，每次加载时候都会直接加载本地或云端的最新资源。

然后编辑器里的profile的设置，如果为local的话，该资源在打母包的时候会一起被打进streamingassets，并且编辑器里用于开发调试的服务器中不会包含这部分内容。
反之，资产不会被打进streamingassets，并且编辑器里用于调试的服务器可以访问到这部分内容。
（实际上，编辑器里调试的服务器只是个普通映射了本地文件目录的http服务器，自己手动把本地文件拷到对应的目录里也是同一回事）

**Comment by young40** [comment]
感谢大佬耐心回复哈, 我先消化一下哈.

大佬, 我加你QQ好友了哈, 方便的话麻烦通过一下哈. QQ名字是, 杨世玲

**Comment by yomunsam** [comment]
> UnityEditor里面能不能完全模拟App启动, 访问更新, 下载更新这些行为?
> 
> 用App不太好用C#调试.

在从streamingassets加载ab包的情况下，大部分热更功能都是能模拟出来的。（完了之后得手动去删掉webvfs下载的东西，或者补丁解压出来的东西，在Application.persistentDataPath的路径）

有QQ的话，也可以直接群里问哦

**Comment by young40** [comment]
尴尬😅, 我确实弄混了补丁包和WebVFS这两种热升级的方式.

不过,
补丁包这种有个比较严重的缺陷, 母包和补丁包之间有关联. 因为要给每一个母包制作一个(系列)的补丁包, 所以可能会限制出母包的数量. 母包数量多了之后, 补丁包的个数会指数级增长.
我们这边就有项目采用了补丁包的方式, 导致这个项目几乎不出新的母包.

WebVFS的边下边玩确实挺吸引人的. 

我这边的热更的基本上, 还是进游戏先下载完成必须的热更的资源.
我们这边之前有, cocos-lua和unity-xlua的, 基于版本的, 也是粒度比较细的热更. 
基于版本可以方便的做灰度和回滚.

不知道大佬对VFS还有没有什么规划?
如果不会再大改VFS的话, 我看能不能试着魔改VFS来用.

**Comment by yomunsam** [comment]
补丁数量这事得看你们用哪种补丁方案了，
1. 每次更新对比上一个版本做一个补丁，更新时候依次下载所有补丁
2. 每次更新对比母包版本做补丁，更新时候下载最新的补丁

后者方案需要下载的补丁数量会少很多，总体积会相对小一点（但并不是很大的差距）。

------

然后，这个谈不上“严重的缺陷”，反而是业内摸索下来总结的目前最佳方案了。或者说，在移动平台App Store和Google play不允许热更新的大前提下偷偷摸摸弄出来的残缺版热更方案，本来就是“能有点用你就算赚了，偷着乐得了”的情况。
补丁是基于母包的，母包和补丁是必须有关联的，当母包中的非热更代码发生变动时候，必然要切分支出新的母包，不然后续热更层的lua或者c#反射不到对应的非热更代码，就崩了。
这是WebVFS也逃不出的问题，在我们的实际实践中，WebVFS也是有母包版本概念的，通过远程资源url区分多套母包版本的云端内容。

管理热更是个大工程，没有银弹。
通常我们观察腾讯网易米哈游的游戏能发现：
1. 不会在同一个母包版本停留太久，适时对外发布新的母包，否则堆了很多补丁之后，用户下载了安装包之后还得读条半天依然是挺劝退的事
2. 不会维护一个母包太久，这一点在《原神》上目前体现很明显，用户在应用商店更新一次之后，一个月左右就会告知用户重新去应用商店更新。

而在背后的开发团队，也需要对热更整体有些意识，采用热更和非热更路线，对应的开发方式都是截然不同的：
1. 对稍大的项目，团队内部需要专门的技术支持部门来编写补丁和母包的管理系统来应对繁杂的补丁版本们。
2. 要适时的取舍，找到留存数据尽可能好看并且不会给开发团队造成负担的方案，必要时果断放弃旧版本母包。
3. 对于小团队，建议尽可能仅用热更新能力做些小修小补

**Comment by young40** [comment]
感谢大佬哈, 我对C#反射这块还不是太熟悉, 我再去多研究研究.
